import { Toaster } from "@/components/ui/toaster";
import AuthProvider from "@/context/AuthProvider";
import I18nProvider from "@/context/I18nProvider";
import TanstackProvider from "@/context/tanstack-provider";
import ThemeSettingsProvider from "@/context/theme-data-provider";
import { ThemeProvider } from "@/context/theme-provider";
import { LANGUAGE_COOKIE, parseLanguage } from "@/lib/i18n/languages";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies } from "next/headers";
import { ToastContainer } from "react-toastify";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const language = parseLanguage(cookieStore.get(LANGUAGE_COOKIE)?.value);
  const themeColor = (cookieStore.get("themeColor")?.value ?? "zinc") as ThemeColor;
  const density = (cookieStore.get("density")?.value ?? "comfortable") as ThemeDensity;
  const radius = (cookieStore.get("radius")?.value ?? "0.5") as ThemeRadius;
  const navDrawerSide = (cookieStore.get("navDrawerSide")?.value ?? "right") as ThemeNavDrawerSide;

  return (
    <html
      lang={language}
      suppressHydrationWarning
      data-theme-color={themeColor}
      data-density={density}
      data-radius={radius}
      translate="no"
    >
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute={"class"}
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider>
            <Toaster />
            <I18nProvider initialLanguage={language}>
              <ThemeSettingsProvider
                initialSettings={{ color: themeColor, density, radius, navDrawerSide }}
              >
                <TanstackProvider>{children}</TanstackProvider>
              </ThemeSettingsProvider>
            </I18nProvider>
            <ToastContainer
              position="bottom-right"
              pauseOnFocusLoss={false}
              pauseOnHover={false}
            />
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
