import { Toaster } from "@/components/ui/toaster";
import AuthProvider from "@/context/AuthProvider";
import I18nProvider from "@/context/I18nProvider";
import TanstackProvider from "@/context/tanstack-provider";
import ThemeDataProvider from "@/context/theme-data-provider";
import { ThemeProvider } from "@/context/theme-provider";
import { getPublicData } from "@/lib/api/api";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const data = await getPublicData(`/api/v1/get-translations`, "translation");
  const translations = data?.data?.translations ?? [];
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute={"class"}
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthProvider>
            <Toaster />
            <I18nProvider translations={translations}>
              <ThemeDataProvider>
                <TanstackProvider>{children}</TanstackProvider>
              </ThemeDataProvider>
            </I18nProvider>
            <ToastContainer
              position="bottom-right"
              pauseOnFocusLoss={false}
              pauseOnHover={false}
            />
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
